### ISSUE TITLE
Could you please advise on how to resolve errors when configuring the environment? Thank you

### ISSUE THREAD

**Issue by Nixizfan** [janne-alatalo/sar-change-detection#2]
C:\Users\Administrator\Desktop\do\project\sar-change-detection\sar-change-detection-master>pip install -r requirements.txt
Looking in indexes: https://mirrors.aliyun.com/pypi/simple
Requirement already satisfied: contourpy==1.2.0 in d:\py3.11.3\lib\site-packages (from -r requirements.txt (line 1)) (1.2.0)
Requirement already satisfied: cycler==0.12.1 in d:\py3.11.3\lib\site-packages (from -r requirements.txt (line 2)) (0.12.1)
Requirement already satisfied: fonttools==4.50.0 in d:\py3.11.3\lib\site-packages (from -r requirements.txt (line 3)) (4.50.0)
Requirement already satisfied: haversine==2.8.1 in c:\users\administrator\appdata\roaming\python\python311\site-packages (from -r requirements.txt (line 4)) (2.8.1)
Requirement already satisfied: kiwisolver==1.4.5 in d:\py3.11.3\lib\site-packages (from -r requirements.txt (line 5)) (1.4.5)
Requirement already satisfied: matplotlib==3.8.3 in d:\py3.11.3\lib\site-packages (from -r requirements.txt (line 6)) (3.8.3)
Requirement already satisfied: numpy==1.26.4 in d:\py3.11.3\lib\site-packages (from -r requirements.txt (line 7)) (1.26.4)
Requirement already satisfied: packaging==24.0 in d:\py3.11.3\lib\site-packages (from -r requirements.txt (line 8)) (24.0)
Requirement already satisfied: pillow==10.2.0 in d:\py3.11.3\lib\site-packages (from -r requirements.txt (line 9)) (10.2.0)
Requirement already satisfied: pyparsing==3.1.2 in d:\py3.11.3\lib\site-packages (from -r requirements.txt (line 10)) (3.1.2)
Requirement already satisfied: python-dateutil==2.9.0.post0 in d:\py3.11.3\lib\site-packages (from -r requirements.txt (line 11)) (2.9.0.post0)
Requirement already satisfied: six==1.16.0 in d:\py3.11.3\lib\site-packages (from -r requirements.txt (line 12)) (1.16.0)
Requirement already satisfied: xxx==0.0.1 in d:\py3.11.3\lib\site-packages (from -r requirements.txt (line 13)) (0.0.1)

**Comment by Nixizfan** [comment]
PS C:\Users\Administrator\Desktop\do\project\sar-change-detection> pip install -r requirements.txt
ERROR: Could not open requirements file: [Errno 2] No such file or directory: 'requirements.txt'

**Comment by janne-alatalo** [comment]
Check that you are in the correct directory when running the `pip install -r requirements.txt` command. The error message says that the pip install command cannot find the `requirements.txt` file, so you are most likely in wrong directory. The `requirements.txt` file is included in the root of this repository.

If you need more assistance with setting up the environment, I would first advice to read tutorials and guides how to use pip. The `pip install -r requirements.txt` is a standard way of setting up Python project dependencies, so there should be plenty of material to learn from.

Hopefully this helps!

**Comment by Nixizfan** [comment]
Thank you very much, if it inspires my paper in the future, I will definitely cite your paper Thank you！
